### ISSUE TITLE
App won't start on macOS 

### ISSUE THREAD

**Issue by jesperstarkar** [SuperFlyTV/sofie-automation-rundown-editor#38]
**Reproduction**
Environment: macOS Monterey 12.1
1. Download [v1.0.1](https://github.com/SuperFlyTV/sofie-automation-rundown-editor/releases/tag/v1.0.1)
2. Right-click the app in the Downloads folder and chose Open [on the first run]

**What happens**
Show Javascript error "Uncaught Exception: Error: SQLITE_CANTOPEN: unable to open database file"
<img width="258" alt="Screenshot 2021-12-17 at 09 47 17" src="https://user-images.githubusercontent.com/6236874/146516432-a4b78416-a764-467f-a790-6a2b11c58c85.png">

**What should happen**
App should open.

**Details**

**Comment by baltedewit** [comment]
This is probably a path issue.

I wonder if the same issue exists on windows too, since this is all I get there:
![image](https://user-images.githubusercontent.com/9898648/146528507-bdd269ee-66a7-4de0-9e01-8ac8e7593f03.png)

**Comment by alvancamp** [comment]
@jesperstarkar can you try [this](https://www.dropbox.com/s/spn0eq7qdmp56wt/sofie-rundown-editor-1.0.2.dmg?dl=0) and let me know how it works?

@baltedewit I haven't been able to repro this issue on Windows. I wonder why it works on my machine but not yours.

**Comment by jesperstarkar** [comment]
Works! Sorry for the late reply.

**Comment by jesperstarkar** [comment]
Perhaps the issue wants to be closed by merging the PR, i don't know.

**Comment by jesperstarkar** [comment]
:)
